# We using focal (Ubuntu 20.04) because only there the unit tests with embedded MongoDB are working
FROM ghcr.io/graalvm/jdk:ol8-java17-22.3.3 as build

WORKDIR /tmp

COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .

RUN --mount=type=cache,target=/root/.m2 \
    ./mvnw -B dependency:resolve-plugins dependency:resolve

COPY src src

RUN --mount=type=cache,target=/root/.m2 \
    ./mvnw -B clean package

FROM ghcr.io/graalvm/jdk:ol8-java17-22.3.3
WORKDIR /workspace/app
ENV PORT 8080
EXPOSE 8080

COPY --from=build /tmp/target/*.war /workspace/app/app.war

ENTRYPOINT exec java $JAVA_OPTS -jar app.war
