---
name: JMeter Test Plan Execution - Updated for JVMs
author: Arne Tarara <arne@green-coding.io>
description: Demonstrating the usage of JMeter executing a test plan.

services:
  gcb-postgres:
    image: postgres:15.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    setup-commands:
     - sleep 20 # wait some time to ensure that the database is ready
  gcb-mongo:
    image: mongo:5.0

  gcb-backend:
    build:
      context: .
      dockerfile: Dockerfile_OpenJ9
    depends_on:
      - gcb-postgres
      - gcb-mongo
    environment:
      MONGO_HOST: gcb-mongo
      POSTGRES_HOST: gcb-postgres
      SPRING_PROFILES_ACTIVE: gmt

  gcb-jmeter:
    image: t2project/jmeter@sha256:8d0543345f747ae512da2f0732fbd0ee760c7168415d2dce87e77d42fd14390a
    environment:
      JVM_XMN: 1g # maximum nursery size
      JVM_XMS: 1g # initial heap size
      JVM_XMX: 2g # maximum heap size



sci:
  R_d: order
  # One order consists of three sequential requests: get inventory, add product to cart, confirm order

flow:
  - name: Execute JMeter test plan # single user orders one product with a short think time of 1 second
    container: gcb-jmeter
    commands:
      - type: console
        command: sleep 20

      - type: console
        command: jmeter -Jhostname=gcb-backend -Jport=8080 -JnumExecutions=5 -JnumUser=5 -JrampUp=0 -JnumProducts=5 -JthinkTimeMin=1000 -JthinkTimeAdditionalRange=0 -JpauseBeforeExecution=0 -JpauseAfterExecution=0 -JloggingEnabled=true -n -t /tmp/repo/jmeter-test-plan.jmx
        log-stdout: true
        read-notes-stdout: true
        read-sci-stdout: true
